x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  env_file:  # PARA los accesos de AWS
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - PYTHONPATH=/opt/airflow
  volumes:
    # Carpetas nativas de Airflow
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    # Carpetas de datos y MLflow (CRUCIAL para la estrategia de las imágenes)
    - ./data:/opt/airflow/data
    - ./mlruns:/opt/airflow/mlruns
    - ./mlflow.db:/opt/airflow/mlflow.db
    - ./src:/opt/airflow/src  # Para que tengan acceso a train_dummy.py y transformers.py
  networks:
    - mlops-network  # Todos los servicios de Airflow usarán esta red
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes: # <--- AÑADE ESTAS DOS LÍNEAS AQUÍ
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mlops-network  # Kafka fase
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  # Servicio para inicializar la base de datos de Airflow la primera vez
  airflow-init:
    <<: *airflow-common
    profiles:
      - init  # <--- Agrega estas dos líneas
    command: version
    environment:
      # REPETIMOS las variables base aquí para evitar que YAML las sobrescriba
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # Variables exclusivas de inicialización
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: kafka
    networks:
      - mlops-network
    ports:
      - "9092:9092" # Puerto para comunicación interna/Docker
      - "9094:9094" # Puerto para comunicación externa (tu PC local)
    environment:
      # Configuración de KRaft
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # Cluster ID Estático: Esto evita el error de InconsistentClusterId para siempre
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      # Red y Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - kafka_data:/bitnami/kafka # Persistencia de datos

  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow  # Dockerfile nuevo
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlflow.db:/app/mlflow.db
    # Usamos el comando exacto que tú usas manualmente
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow.db 
      --artifacts-destination ./mlruns 
      --serve-artifacts 
      --host 0.0.0.0 
      --port 5000
    networks:
      - mlops-network

  fraud-producer:
    build:
      context: .
      dockerfile: Dockerfile.streaming
    container_name: fraud-producer
    env_file:  # Para los accesos de AWS
      - .env
    volumes:
      - .:/app  # Sincronizamos código para que edites en Windows y se vea en Docker
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - kafka
    networks:
      - mlops-network
    command: python -m src.streaming.producer

  fraud-consumer:
    build:
      context: .
      dockerfile: Dockerfile.streaming
    container_name: fraud-consumer
    env_file:  # Para los accesos de AWS
      - .env
    volumes:
      - .:/app
    environment:
      - KAFKA_BROKER=kafka:9092
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - JDK_JAVA_OPTIONS=--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
      - PYSPARK_SUBMIT_ARGS=--conf spark.driver.extraJavaOptions=-Dio.netty.tryReflectionSetAccessible=true --conf spark.executor.extraJavaOptions=-Dio.netty.tryReflectionSetAccessible=true pyspark-shell
    depends_on:
      - kafka
      - mlflow-server
    networks:
      - mlops-network
    command: python -m src.streaming.consumer


# --- DECLARACIÓN GLOBAL DE REDES Y VOLÚMENES FASE KAFKA ---
networks:
  mlops-network:
    driver: bridge # Esta es la parte que faltaba para corregir el error

volumes:
  postgres-data:
  kafka_data:
    driver: local
    